In [62]:
import pandas as pd
import requests
import json

pd.options.display.max_columns = 30

In [63]:
def page_url(page=1):
    '''
    Uses default query specifications
    '''
    api_key  = "api_key=d2ba87d601823962c8cc04aa877278a1"
    discover_api = "https://api.themoviedb.org/3/discover/movie?"
    query = "&language=en-US&sort_by=popularity.desc&include_adult=false&page={}&vote_count.gte=500".format(page)
    url = discover_api + api_key + query
    return url

In [64]:
url = discover_api + api_key + default_query

def make_big_dataframe(max_pages):
    '''
    The API proides data in pages of 10 movies per url request. 
    This function iterates over each page adding the data to one big pandas df
    '''
    if (max_pages >= 214):
        print("max is 213")
        return
    
    frames = []
    
    for page_num in range(1,max_pages+1):
        url = page_url(page_num)
        r = requests.get(url)
        if r.status_code != 200:
            '''Something went wrong'''
            print("Error")
            return
        data = r.json()
        page_df = pd.json_normalize(data = data, record_path = "results") # normalize, as you convert to df
        frames.append(page_df)
       
    # concat dfs into one
    df = pd.concat(frames) # method takes array of df
    
    # process
    df = df.reset_index() # (else they restart at 19)
    df =df[["title",
            "genre_ids",
            "release_date",
            "overview",
            "popularity",
            "vote_count",
            "poster_path",
            "vote_average"]]
    
    return df  

test_frame = make_big_dataframe(10)
# functional

In [68]:
df = test_frame
df

,title,genre_ids,release_date,overview,popularity,vote_count,poster_path,vote_average
0,Ad Astra,"[18, 878]",2019-09-17,"The near future, a time when both hope and har...",165.765,3802,/xBHvZcjRiWyobQ9kxBhO6B2dtRI.jpg,6.1
1,Sonic the Hedgehog,"[28, 35, 878, 10751]",2020-02-12,Based on the global blockbuster videogame fran...,117.793,4784,/aQvJ5WPzZgYVDrxLX4R6cLJCEaQ.jpg,7.5
2,Parasite,"[35, 18, 53]",2019-05-30,"All unemployed, Ki-taek's family takes peculia...",96.606,8123,/7IiTTgloJzvGI1TAYymCfbfl3vT.jpg,8.5
3,Avengers: Infinity War,"[28, 12, 878]",2018-04-25,As the Avengers and their allies have continue...,82.688,18663,/7WsyChQLEftFiDOVTGkv3hFpyyt.jpg,8.3
4,The Invisible Man,"[27, 878, 53]",2020-02-26,When Cecilia's abusive ex takes his own life a...,94.348,2225,/5EufsDwXdY2CVttYOk2WtYhgKpa.jpg,7.2
...,...,...,...,...,...,...,...,...
195,Thor,"[28, 12, 14]",2011-04-21,"Against his father Odin's will, The Mighty Tho...",27.471,15015,/prSfAi1xGrhLQNxVSUFh61xQ4Qy.jpg,6.7
196,Alien: Covenant,"[27, 878]",2017-05-09,Bound for a remote planet on the far side of t...,25.225,5795,/zecMELPbU5YMQpC81Z8ImaaXuf9.jpg,5.9
197,The Mask,"[35, 80, 14, 10749]",1994-07-29,When timid bank clerk Stanley Ipkiss discovers...,34.309,6684,/yd3wjLLeQHJ3oRDy4wwiNNFVyLW.jpg,6.9
198,Mission: Impossible - Fallout,"[28, 12]",2018-07-13,"When an IMF mission ends badly, the world is f...",32.475,5100,/AkJQpZp9WoNdj7pLYSj1L0RcMMN.jpg,7.3
199,2001: A Space Odyssey,"[878, 9648, 12]",1968-04-09,Humanity finds a mysterious object buried bene...,28.199,7359,/zmmYdPa8Lxx999Af9vnVP4XQ1V6.jpg,8.1

### Now the ML processing starts

In [69]:
 ## add a column with the concatenation of TITLE and OVERVIEW

In [70]:
import numpy as np
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.metrics.pairwise import cosine_similarity

In [71]:
FEATURES = ["title", "overview"]

def combine_features(row):
    combined_str = ""
    for feat in FEATURES:
        combined_str += row[feat] + " "
    return combined_str


# at a global level (to add the combined features)
# apply is like map for each row
df["combined_features"] = df.apply(combine_features,axis=1) #applying combined_features() method over each rows of dataframe and storing the combined string in "combined_features" column

In [72]:
df

,title,genre_ids,release_date,overview,popularity,vote_count,poster_path,vote_average,combined_features
0,Ad Astra,"[18, 878]",2019-09-17,"The near future, a time when both hope and har...",165.765,3802,/xBHvZcjRiWyobQ9kxBhO6B2dtRI.jpg,6.1,"Ad Astra The near future, a time when both hop..."
1,Sonic the Hedgehog,"[28, 35, 878, 10751]",2020-02-12,Based on the global blockbuster videogame fran...,117.793,4784,/aQvJ5WPzZgYVDrxLX4R6cLJCEaQ.jpg,7.5,Sonic the Hedgehog Based on the global blockbu...
2,Parasite,"[35, 18, 53]",2019-05-30,"All unemployed, Ki-taek's family takes peculia...",96.606,8123,/7IiTTgloJzvGI1TAYymCfbfl3vT.jpg,8.5,"Parasite All unemployed, Ki-taek's family take..."
3,Avengers: Infinity War,"[28, 12, 878]",2018-04-25,As the Avengers and their allies have continue...,82.688,18663,/7WsyChQLEftFiDOVTGkv3hFpyyt.jpg,8.3,Avengers: Infinity War As the Avengers and the...
4,The Invisible Man,"[27, 878, 53]",2020-02-26,When Cecilia's abusive ex takes his own life a...,94.348,2225,/5EufsDwXdY2CVttYOk2WtYhgKpa.jpg,7.2,The Invisible Man When Cecilia's abusive ex ta...
...,...,...,...,...,...,...,...,...,...
195,Thor,"[28, 12, 14]",2011-04-21,"Against his father Odin's will, The Mighty Tho...",27.471,15015,/prSfAi1xGrhLQNxVSUFh61xQ4Qy.jpg,6.7,"Thor Against his father Odin's will, The Might..."
196,Alien: Covenant,"[27, 878]",2017-05-09,Bound for a remote planet on the far side of t...,25.225,5795,/zecMELPbU5YMQpC81Z8ImaaXuf9.jpg,5.9,Alien: Covenant Bound for a remote planet on t...
197,The Mask,"[35, 80, 14, 10749]",1994-07-29,When timid bank clerk Stanley Ipkiss discovers...,34.309,6684,/yd3wjLLeQHJ3oRDy4wwiNNFVyLW.jpg,6.9,The Mask When timid bank clerk Stanley Ipkiss ...
198,Mission: Impossible - Fallout,"[28, 12]",2018-07-13,"When an IMF mission ends badly, the world is f...",32.475,5100,/AkJQpZp9WoNdj7pLYSj1L0RcMMN.jpg,7.3,Mission: Impossible - Fallout When an IMF miss...
199,2001: A Space Odyssey,"[878, 9648, 12]",1968-04-09,Humanity finds a mysterious object buried bene...,28.199,7359,/zmmYdPa8Lxx999Af9vnVP4XQ1V6.jpg,8.1,2001: A Space Odyssey Humanity finds a mysteri...

In [83]:
# now feed combined_features strings into CountVectorize object
cv = CountVectorizer()
count_matrix = cv.fit_transform(df["combined_features"])

In [84]:
count_matrix

<200x3223 sparse matrix of type '<class 'numpy.int64'>'
	with 8404 stored elements in Compressed Sparse Row format>

In [85]:
#print(cv.get_feature_names())
#print(count_matrix.toarray())

In [88]:
## get cosine similarity matrix
cosine_matrix = cosine_similarity(count_matrix)
cosine_matrix   # symmetrical matrix with diagonals = 1 (100 similar to each other)

array([[1.        , 0.44984383, 0.19820624, ..., 0.40729903, 0.41024184,
        0.45457002],
       [0.44984383, 1.        , 0.19813746, ..., 0.43294434, 0.40560277,
        0.38781737],
       [0.19820624, 0.19813746, 1.        , ..., 0.16145842, 0.1711842 ,
        0.12427395],
       ...,
       [0.40729903, 0.43294434, 0.16145842, ..., 1.        , 0.29021087,
        0.35113883],
       [0.41024184, 0.40560277, 0.1711842 , ..., 0.29021087, 1.        ,
        0.29783232],
       [0.45457002, 0.38781737, 0.12427395, ..., 0.35113883, 0.29783232,
        1.        ]])

In [117]:
# HELPER functions
def get_title_from_index(index, df):
    return df[df.index == index]["title"].values[0]
def get_index_from_title(title, df):
    # should iterate over all and see if coantains string
    title = title.title()
    return df[df.title == title].index.values[0]

print(get_title_from_index(4, df))
print(get_index_from_title("Thor", df))
print(get_index_from_title("Avatar", df))

The Invisible Man
195
126

Our next step is to get the title of the movie that the user currently likes. Then we will find the index of that movie. After that, we will access the row corresponding to this movie in the similarity matrix. Thus, we will get the similarity scores of all other movies from the current movie. Then we will enumerate through all the similarity scores of that movie to make a tuple of movie index and similarity score. This will convert a row of similarity scores like this- [1 0.5 0.2 0.9] to this- [(0, 1) (1, 0.5) (2, 0.2) (3, 0.9)] . Here, each item is in this form- (movie index, similarity score).

In [121]:
movie_user_likes = "Avatar"
movie_index = get_index_from_title(movie_user_likes, df)
similar_movies = list(enumerate(cosine_matrix[movie_index])) 
# accessing the row corresponding to given movie to find all the similarity scores
# for that movie and then enumerating over it
similar_movies  ## list of tuples (movie_index, similarity score to movie_user_likes)

[(0, 0.37181247169316833),
 (1, 0.32448554053666706),
 (2, 0.2105587219030789),
 (3, 0.2856851356570029),
 (4, 0.1287565506561512),
 (5, 0.2586032735340944),
 (6, 0.35349605916013666),
 (7, 0.29821002598961344),
 (8, 0.18832944617230332),
 (9, 0.16081688022566923),
 (10, 0.18761969359661412),
 (11, 0.3062059890175074),
 (12, 0.17868542247296582),
 (13, 0.1939524551505708),
 (14, 0.28661838988431687),
 (15, 0.304275935729018),
 (16, 0.3011721230063664),
 (17, 0.2495492591311128),
 (18, 0.22287124708010464),
 (19, 0.27429019252949666),
 (20, 0.17855051462249658),
 (21, 0.25997347344787264),
 (22, 0.33765162622095446),
 (23, 0.24675590100659828),
 (24, 0.36594210704893765),
 (25, 0.3652311999283316),
 (26, 0.2394201085048437),
 (27, 0.161627045958809),
 (28, 0.36883813286720696),
 (29, 0.20632815353005762),
 (30, 0.23932498098297528),
 (31, 0.3032392174315614),
 (32, 0.2214546129433066),
 (33, 0.20057388927143846),
 (34, 0.3376516262209545),
 (35, 0.3304993437657777),
 (36, 0.3210274757266731),
 (37, 0.37820575262078365),
 (38, 0.39868420696101237),
 (39, 0.2608794285202369),
 (40, 0.3011721230063664),
 (41, 0.2603125627255638),
 (42, 0.3048310352844594),
 (43, 0.24382992454708535),
 (44, 0.2573374643010911),
 (45, 0.18569533817705186),
 (46, 0.2785430072655778),
 (47, 0.29626726898333944),
 (48, 0.30391533692741546),
 (49, 0.3013845259203858),
 (50, 0.32600993113823357),
 (51, 0.3394167965134989),
 (52, 0.2081453617075184),
 (53, 0.273336136795267),
 (54, 0.30574067067809085),
 (55, 0.33259278156261735),
 (56, 0.37523938719322814),
 (57, 0.2503915429180672),
 (58, 0.15488061853247326),
 (59, 0.14037248126871926),
 (60, 0.2014148736276902),
 (61, 0.21971768720102058),
 (62, 0.3237996688322592),
 (63, 0.2615343689010107),
 (64, 0.29735051672502627),
 (65, 0.29821002598961344),
 (66, 0.24034556122481557),
 (67, 0.32000522461774605),
 (68, 0.25628391481282986),
 (69, 0.3662346092966271),
 (70, 0.2250967420452386),
 (71, 0.24249160368647651),
 (72, 0.22395700438234173),
 (73, 0.2464135551870271),
 (74, 0.32810591327802474),
 (75, 0.2844972711960656),
 (76, 0.26468888905891474),
 (77, 0.15746933183579126),
 (78, 0.20215947828770758),
 (79, 0.1432670637653132),
 (80, 0.2409900932515112),
 (81, 0.28709267411827166),
 (82, 0.35959747611403803),
 (83, 0.1592324388246205),
 (84, 0.2549249642552304),
 (85, 0.20405773099713895),
 (86, 0.2906591794880899),
 (87, 0.40585624702096074),
 (88, 0.3222637978043043),
 (89, 0.19340379081188955),
 (90, 0.21398266546446335),
 (91, 0.252310280118708),
 (92, 0.24607943495851856),
 (93, 0.34776361258027355),
 (94, 0.2815505451474917),
 (95, 0.2952549971921086),
 (96, 0.3855289616378948),
 (97, 0.22983614055242746),
 (98, 0.2746806413997892),
 (99, 0.1650625228240461),
 (100, 0.27579867425734583),
 (101, 0.2807449625374385),
 (102, 0.20802038699693748),
 (103, 0.28983290224945424),
 (104, 0.34045327482409776),
 (105, 0.29180695999251005),
 (106, 0.26681493838602804),
 (107, 0.29180695999251005),
 (108, 0.07252642155445858),
 (109, 0.24072846024282474),
 (110, 0.12456821978060995),
 (111, 0.3677315656764611),
 (112, 0.36030187928883595),
 (113, 0.2913428162916919),
 (114, 0.25168100511526903),
 (115, 0.306381676672686),
 (116, 0.3282660821493064),
 (117, 0.338446709524953),
 (118, 0.2194469320923768),
 (119, 0.19795189561622392),
 (120, 0.32912131438150566),
 (121, 0.17400443716972247),
 (122, 0.2755713307126347),
 (123, 0.2533593918376833),
 (124, 0.22292541435446867),
 (125, 0.13689641954834839),
 (126, 0.9999999999999997),
 (127, 0.25788071477756375),
 (128, 0.21531408048872458),
 (129, 0.16208817969462155),
 (130, 0.26424909878161656),
 (131, 0.2526993478596345),
 (132, 0.20633868020813542),
 (133, 0.35377908700348826),
 (134, 0.37164566483340783),
 (135, 0.27333613679526697),
 (136, 0.337941364303121),
 (137, 0.297112541083283),
 (138, 0.2375422747394687),
 (139, 0.2829999783819469),
 (140, 0.32273336625880605),
 (141, 0.21442250696755893),
 (142, 0.3221916685210339),
 (143, 0.3995746439394742),
 (144, 0.3315938128703508),
 (145, 0.2173399540921557),
 (146, 0.2503242243141034),
 (147, 0.23176179118107215),
 (148, 0.25384037467818854),
 (149, 0.2653343152526162),
 (150, 0.2060104810498419),
 (151, 0.30016680568428156),
 (152, 0.28577909557918063),
 (153, 0.3277606683281533),
 (154, 0.27333613679526697),
 (155, 0.28326441144353265),
 (156, 0.31583808285461834),
 (157, 0.339502302698635),
 (158, 0.3207464932149077),
 (159, 0.23488808780588138),
 (160, 0.26339329200376005),
 (161, 0.31900813481115786),
 (162, 0.29829152269602843),
 (163, 0.1450036976414354),
 (164, 0.29821002598961344),
 (165, 0.23402293537155466),
 (166, 0.3543059966305303),
 (167, 0.2751053211988152),
 (168, 0.2858966759567453),
 (169, 0.2888741522913896),
 (170, 0.24422500434906544),
 (171, 0.2626128657194451),
 (172, 0.14016830300607283),
 (173, 0.25507216374642366),
 (174, 0.22194838080923762),
 (175, 0.31145857161752355),
 (176, 0.3319062115909338),
 (177, 0.18923271008903098),
 (178, 0.24759378423606915),
 (179, 0.175195446534857),
 (180, 0.29361010975735174),
 (181, 0.2799462554779272),
 (182, 0.25477190211939277),
 (183, 0.25486446230486953),
 (184, 0.16413304107465318),
 (185, 0.21893716009046157),
 (186, 0.24898915226512977),
 (187, 0.360432779158473),
 (188, 0.28602803212078903),
 (189, 0.3131841170745085),
 (190, 0.2754306972098739),
 (191, 0.14680505487867587),
 (192, 0.27690930984749823),
 (193, 0.16000261230887303),
 (194, 0.2770588731486592),
 (195, 0.26396306930176416),
 (196, 0.3761086016708255),
 (197, 0.2697053980955753),
 (198, 0.315387850148385),
 (199, 0.24422500434906544)]

In [124]:
# sort
# [from:to] notation
# labda var : var[1] (tuple is (0,1)) so you are sorting based on similarity scores
sorted_similar_movies = sorted(similar_movies,key=lambda x:x[1],reverse=True)
sorted_similar_movies

## boom we done

[(126, 0.9999999999999997),
 (87, 0.40585624702096074),
 (143, 0.3995746439394742),
 (38, 0.39868420696101237),
 (96, 0.3855289616378948),
 (37, 0.37820575262078365),
 (196, 0.3761086016708255),
 (56, 0.37523938719322814),
 (0, 0.37181247169316833),
 (134, 0.37164566483340783),
 (28, 0.36883813286720696),
 (111, 0.3677315656764611),
 (69, 0.3662346092966271),
 (24, 0.36594210704893765),
 (25, 0.3652311999283316),
 (187, 0.360432779158473),
 (112, 0.36030187928883595),
 (82, 0.35959747611403803),
 (166, 0.3543059966305303),
 (133, 0.35377908700348826),
 (6, 0.35349605916013666),
 (93, 0.34776361258027355),
 (104, 0.34045327482409776),
 (157, 0.339502302698635),
 (51, 0.3394167965134989),
 (117, 0.338446709524953),
 (136, 0.337941364303121),
 (34, 0.3376516262209545),
 (22, 0.33765162622095446),
 (55, 0.33259278156261735),
 (176, 0.3319062115909338),
 (144, 0.3315938128703508),
 (35, 0.3304993437657777),
 (120, 0.32912131438150566),
 (116, 0.3282660821493064),
 (74, 0.32810591327802474),
 (153, 0.3277606683281533),
 (50, 0.32600993113823357),
 (1, 0.32448554053666706),
 (62, 0.3237996688322592),
 (140, 0.32273336625880605),
 (88, 0.3222637978043043),
 (142, 0.3221916685210339),
 (36, 0.3210274757266731),
 (158, 0.3207464932149077),
 (67, 0.32000522461774605),
 (161, 0.31900813481115786),
 (156, 0.31583808285461834),
 (198, 0.315387850148385),
 (189, 0.3131841170745085),
 (175, 0.31145857161752355),
 (115, 0.306381676672686),
 (11, 0.3062059890175074),
 (54, 0.30574067067809085),
 (42, 0.3048310352844594),
 (15, 0.304275935729018),
 (48, 0.30391533692741546),
 (31, 0.3032392174315614),
 (49, 0.3013845259203858),
 (16, 0.3011721230063664),
 (40, 0.3011721230063664),
 (151, 0.30016680568428156),
 (162, 0.29829152269602843),
 (7, 0.29821002598961344),
 (65, 0.29821002598961344),
 (164, 0.29821002598961344),
 (64, 0.29735051672502627),
 (137, 0.297112541083283),
 (47, 0.29626726898333944),
 (95, 0.2952549971921086),
 (180, 0.29361010975735174),
 (105, 0.29180695999251005),
 (107, 0.29180695999251005),
 (113, 0.2913428162916919),
 (86, 0.2906591794880899),
 (103, 0.28983290224945424),
 (169, 0.2888741522913896),
 (81, 0.28709267411827166),
 (14, 0.28661838988431687),
 (188, 0.28602803212078903),
 (168, 0.2858966759567453),
 (152, 0.28577909557918063),
 (3, 0.2856851356570029),
 (75, 0.2844972711960656),
 (155, 0.28326441144353265),
 (139, 0.2829999783819469),
 (94, 0.2815505451474917),
 (101, 0.2807449625374385),
 (181, 0.2799462554779272),
 (46, 0.2785430072655778),
 (194, 0.2770588731486592),
 (192, 0.27690930984749823),
 (100, 0.27579867425734583),
 (122, 0.2755713307126347),
 (190, 0.2754306972098739),
 (167, 0.2751053211988152),
 (98, 0.2746806413997892),
 (19, 0.27429019252949666),
 (53, 0.273336136795267),
 (135, 0.27333613679526697),
 (154, 0.27333613679526697),
 (197, 0.2697053980955753),
 (106, 0.26681493838602804),
 (149, 0.2653343152526162),
 (76, 0.26468888905891474),
 (130, 0.26424909878161656),
 (195, 0.26396306930176416),
 (160, 0.26339329200376005),
 (171, 0.2626128657194451),
 (63, 0.2615343689010107),
 (39, 0.2608794285202369),
 (41, 0.2603125627255638),
 (21, 0.25997347344787264),
 (5, 0.2586032735340944),
 (127, 0.25788071477756375),
 (44, 0.2573374643010911),
 (68, 0.25628391481282986),
 (173, 0.25507216374642366),
 (84, 0.2549249642552304),
 (183, 0.25486446230486953),
 (182, 0.25477190211939277),
 (148, 0.25384037467818854),
 (123, 0.2533593918376833),
 (131, 0.2526993478596345),
 (91, 0.252310280118708),
 (114, 0.25168100511526903),
 (57, 0.2503915429180672),
 (146, 0.2503242243141034),
 (17, 0.2495492591311128),
 (186, 0.24898915226512977),
 (178, 0.24759378423606915),
 (23, 0.24675590100659828),
 (73, 0.2464135551870271),
 (92, 0.24607943495851856),
 (170, 0.24422500434906544),
 (199, 0.24422500434906544),
 (43, 0.24382992454708535),
 (71, 0.24249160368647651),
 (80, 0.2409900932515112),
 (109, 0.24072846024282474),
 (66, 0.24034556122481557),
 (26, 0.2394201085048437),
 (30, 0.23932498098297528),
 (138, 0.2375422747394687),
 (159, 0.23488808780588138),
 (165, 0.23402293537155466),
 (147, 0.23176179118107215),
 (97, 0.22983614055242746),
 (70, 0.2250967420452386),
 (72, 0.22395700438234173),
 (124, 0.22292541435446867),
 (18, 0.22287124708010464),
 (174, 0.22194838080923762),
 (32, 0.2214546129433066),
 (61, 0.21971768720102058),
 (118, 0.2194469320923768),
 (185, 0.21893716009046157),
 (145, 0.2173399540921557),
 (128, 0.21531408048872458),
 (141, 0.21442250696755893),
 (90, 0.21398266546446335),
 (2, 0.2105587219030789),
 (52, 0.2081453617075184),
 (102, 0.20802038699693748),
 (132, 0.20633868020813542),
 (29, 0.20632815353005762),
 (150, 0.2060104810498419),
 (85, 0.20405773099713895),
 (78, 0.20215947828770758),
 (60, 0.2014148736276902),
 (33, 0.20057388927143846),
 (119, 0.19795189561622392),
 (13, 0.1939524551505708),
 (89, 0.19340379081188955),
 (177, 0.18923271008903098),
 (8, 0.18832944617230332),
 (10, 0.18761969359661412),
 (45, 0.18569533817705186),
 (12, 0.17868542247296582),
 (20, 0.17855051462249658),
 (179, 0.175195446534857),
 (121, 0.17400443716972247),
 (99, 0.1650625228240461),
 (184, 0.16413304107465318),
 (129, 0.16208817969462155),
 (27, 0.161627045958809),
 (9, 0.16081688022566923),
 (193, 0.16000261230887303),
 (83, 0.1592324388246205),
 (77, 0.15746933183579126),
 (58, 0.15488061853247326),
 (191, 0.14680505487867587),
 (163, 0.1450036976414354),
 (79, 0.1432670637653132),
 (59, 0.14037248126871926),
 (172, 0.14016830300607283),
 (125, 0.13689641954834839),
 (4, 0.1287565506561512),
 (110, 0.12456821978060995),
 (108, 0.07252642155445858)]

In [125]:
i = 0

for tup in sorted_similar_movies:
    index, score =  tup
    print(get_title_from_index(index, df))
    i+=1
    if i > 5:
        break

Avatar
Brave
Avengers: Age of Ultron
Thor: Ragnarok
The Hot Chick
The Lord of the Rings: The Return of the King

In [ ]:
### instead of this forloop, we would get entire rows by index and output that to HTML